### ISSUE TITLE
Module 'AppTrackingTransparency' not found

### ISSUE THREAD

**Issue by houdzaiw** [Koppel-Zhou/react-native-baidu-trace#1]

**Comment by Koppel-Zhou** [comment]
The problem you encountered should not be a problem with this library，Please check the settings for application permissions in your project. [Here](https://www.npmjs.com/package/react-native-permissions) is the manual for `react-native-permissions`.

**Comment by houdzaiw** [comment]
> The problem you encountered should not be a problem with this library，Please check the settings for application permissions in your project. [Here](https://www.npmjs.com/package/react-native-permissions) is the manual for `react-native-permissions`.

好的，谢谢
